# Switches 
set_property PACKAGE_PIN R2 [get_ports {digit[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}] 
set_property PACKAGE_PIN T1 [get_ports {digit[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]

set_property PACKAGE_PIN U1 [get_ports {value[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {value[3]}]
set_property PACKAGE_PIN W2 [get_ports {value[2]}] 	 	 	
 	set_property IOSTANDARD LVCMOS33 [get_ports {value[2]}]
set_property PACKAGE_PIN R3 [get_ports {value[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {value[1]}] 
 set_property PACKAGE_PIN T2 [get_ports {value[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {value[0]}]
 
 set_property PACKAGE_PIN T3 [get_ports {loadDig}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {loadDig}]
 	
 set_property PACKAGE_PIN W13 [get_ports {part[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {part[1]}] 
set_property PACKAGE_PIN W14 [get_ports {part[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {part[0]}]
 	
set_property PACKAGE_PIN V15 [get_ports {loadSS}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {loadSS}]
 	
 set_property PACKAGE_PIN W15 [get_ports {restart}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {restart}] 
set_property PACKAGE_PIN W17 [get_ports {reset}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
 	
# Buttons
set_property PACKAGE_PIN U18 [get_ports {start}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {start}]
 	
set_property PACKAGE_PIN T18 [get_ports {b1}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {b1}]
set_property PACKAGE_PIN T17 [get_ports {b2}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {b2}]
set_property PACKAGE_PIN U17 [get_ports {b3}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {b3}]
set_property PACKAGE_PIN W19 [get_ports {b4}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {b4}]

# LEDs
set_property PACKAGE_PIN L1 [get_ports {ssLED[15]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[15]}] 
set_property PACKAGE_PIN P1 [get_ports {ssLED[14]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[14]}] 
set_property PACKAGE_PIN N3 [get_ports {ssLED[13]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[13]}]
set_property PACKAGE_PIN P3 [get_ports {ssLED[12]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[12]}]
set_property PACKAGE_PIN U3 [get_ports {ssLED[11]}] 	 	 	
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[11]}]
set_property PACKAGE_PIN W3 [get_ports {ssLED[10]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[10]}] 
set_property PACKAGE_PIN V3 [get_ports {ssLED[9]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[9]}]
set_property PACKAGE_PIN V13 [get_ports {ssLED[8]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[8]}]
set_property PACKAGE_PIN V14 [get_ports {ssLED[7]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[7]}]
set_property PACKAGE_PIN U14 [get_ports {ssLED[6]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[6]}] 
set_property PACKAGE_PIN U15 [get_ports {ssLED[5]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[5]}]
set_property PACKAGE_PIN W18 [get_ports {ssLED[4]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[4]}]
set_property PACKAGE_PIN V19 [get_ports {ssLED[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[3]}]
set_property PACKAGE_PIN U19 [get_ports {ssLED[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[2]}]
set_property PACKAGE_PIN E19 [get_ports {ssLED[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[1]}] 
set_property PACKAGE_PIN U16 [get_ports {ssLED[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {ssLED[0]}]
 	
# Clock signal 
set_property PACKAGE_PIN W5 [get_ports clk]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports clk]
 	
#7 segment display 
set_property PACKAGE_PIN W7 [get_ports {a}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {a}] 
set_property PACKAGE_PIN W6 [get_ports {b}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {b}] 
set_property PACKAGE_PIN U8 [get_ports {c}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {c}] 
set_property PACKAGE_PIN V8 [get_ports {d}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {d}] 
set_property PACKAGE_PIN U5 [get_ports {e}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {e}] 
set_property PACKAGE_PIN V5 [get_ports {f}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {f}] 
set_property PACKAGE_PIN U7 [get_ports {g}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {g}] 
set_property PACKAGE_PIN V7 [get_ports dp]  	 	 	 	  
 	set_property IOSTANDARD LVCMOS33 [get_ports dp] 
set_property PACKAGE_PIN U2 [get_ports {an[0]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}] 
set_property PACKAGE_PIN U4 [get_ports {an[1]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}] 
set_property PACKAGE_PIN V4 [get_ports {an[2]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}] 
set_property PACKAGE_PIN W4 [get_ports {an[3]}] 	 	 	 	 	 
 	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]

set_property PACKAGE_PIN A14 [get_ports {rowsOut[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[0]}] 
set_property PACKAGE_PIN A16 [get_ports {rowsOut[1]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[1]}] 
set_property PACKAGE_PIN B15 [get_ports {rowsOut[2]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[2]}] 
set_property PACKAGE_PIN B16 [get_ports {rowsOut[3]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[3]}] 
set_property PACKAGE_PIN A15 [get_ports {rowsOut[4]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[4]}] 
set_property PACKAGE_PIN A17 [get_ports {rowsOut[5]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[5]}] 
set_property PACKAGE_PIN C15 [get_ports {rowsOut[6]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[6]}]  
set_property PACKAGE_PIN C16 [get_ports {rowsOut[7]}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {rowsOut[7]}]
set_property PACKAGE_PIN K17 [get_ports {ds}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {ds}]
set_property PACKAGE_PIN M18 [get_ports {oe}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {oe}] 
set_property PACKAGE_PIN N17 [get_ports {stcp}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {stcp}]  
set_property PACKAGE_PIN P18 [get_ports {shcp}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {shcp}] 
set_property PACKAGE_PIN L17 [get_ports {mr}]
  	set_property IOSTANDARD LVCMOS33 [get_ports {mr}] 